#更新fork
name: 自动同步

on:
   repository_dispatch:
   workflow_dispatch:
   schedule:
     - cron: '55 7 * * *' #设置定时任务
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 检查仓库
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.WORKFLOW_TOKEN }}
    - name: 设置环境
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "96098265+github-actions[bot]@users.noreply.github.com"
    - name: 同步上游master分支更新
      run: |
        git remote add upstream https://github.com/BtbN/FFmpeg-Builds.git
        git remote -v
        git fetch upstream
        git checkout master || git checkout -b master origin/master
        git merge --strategy-option=ours upstream/master
        git push -f origin master
